services:
  - type: web
    name: geolertfrontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve dist -s -l $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://geolertbackend.onrender.com